name: Run Unit Tests and Report Coverage

on:
  pull_request:
    branches: [ main ]

permissions:
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        
    - name: Install dependencies
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi
      
    - name: Run tests
      id: test
      run: |
        echo "test_output<<EOF" >> $GITHUB_OUTPUT
        npm test 2>&1 | tee test_output.log
        echo "EOF" >> $GITHUB_OUTPUT
      continue-on-error: true

    - name: Comment PR
      uses: actions/github-script@v6
      if: always()
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const testOutput = process.env.TEST_OUTPUT
          
          const comment = `## Test Results

          \`\`\`
          ${testOutput}
          \`\`\`
          `
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          })
      env:
        TEST_OUTPUT: ${{ steps.test.outputs.test_output }}